image: node:8.9.4

cache:
  paths:
  - node_modules/

stages:
  - test
  - build

test:
  stage: test
  script:
   - npm install -g yarn
   - yarn install
   - yarn run test
   - yarn run lint

build:
  stage: build
  script:
   - npm install -g yarn
   - yarn install
   - yarn run package
  artifacts:
    paths:
      - build/passvault.zip
      - build/passvault.xpi