#! /bin/bash
# set -e

#Make sure we have our client configured to talk to vault
vault status

#Make sure we are logged in
vault auth list

#PassVault backend
vault secrets enable -path passvault kv

#Write test user policy
vault policy write test test-policy.hcl

#Setup userpass w/ test user
vault auth enable userpass
vault write auth/userpass/users/test password=test policies=test

#Test Data
vault write passvault/test/preferences favorites=default/%%%google.com,code/%%%gitlab.com
vault write passvault/test/passwords/default/google.com username=bob@gmail.com password=foo notes="test note" url="google.com/login"
vault write passvault/test/passwords/code/gitlab.com username=test password=foo url=gitlab.com
